import jsPDF from "jspdf";
import "jspdf-autotable";
import moment from "moment";
import { LeaveMap } from "../../config";

const generatePDF = (leaves) => {
  const doc = new jsPDF();
  const tableColumn = [
    "Idx",
    "Leave_category",
    "Description",
    "Start_date",
    "End_date",
    "Status",
  ];

  const tableRows = [];
  leaves.forEach((leave, idx) => {
    const leaveData = [
      idx + 1,
      LeaveMap[leave.leaveType],
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
      moment(Number(leave?.startDate)).format("MMM  D,  YYYY"),
      moment(Number(leave?.endDate)).format("MMM  D,  YYYY"),
      leave.status,
    ];
    tableRows.push(leaveData);
  });

  doc.autoTable(tableColumn, tableRows, {
    startY: 20,
    headStyles: { fillColor: "#455a64" },
  });
  const date = Date.now();
  const dateStr = moment(date).format("MMM  D,  YYYY");

  var img = new Image();
  img.src = "/assets/img/logo.png";
  doc.addImage(img, "png", 184, 7, 12, 12);
  doc.setFontSize(12);

  doc.text("Report generated by LU leave app", 14, 15);
  doc.save(`report_${dateStr}.pdf`);
};

export default generatePDF;